package com.eplvc.eplvcservice.lead;

public enum Status {

	SERVED,
	LOADED,
	POLICY_NAME_VERIFIED,
	POLICY_NAME_MODIFICATION_REQUESTED,
	POLICY_DETAILS_VERIFIED,
	POLICY_DETAILS_MODIFICATION_REQUESTED
}
